# General Description
experiment_name: "IRL"
task: "motion forecasting"
dataset: "highD"

# Model Configuration
model1:
  class: "IRLRewardModel"
  module: "models.IRLmodel"
  num_inputs: 5
  num_hidden: 32
  num_outputs: 2
  pred_hrz: 25

model2:
  class: "IRLTrajectoryPredictor"
  module: "models.IRLmodel"

# Lightning Module Configuration
litmodule:
  class: "IRLLitModel"
  module: "base"

# Data Module Configuration
datamodule:
  class: "DroneDataModule"
  module: "datamodules.dataloader"
  batch_size: 128
  root: "data/"
  name: "highD"
  transform: null

# Training Configuration
training:
  dataset: "highD"
  epochs: 3
  lr: 0.0005